using AdminHelper.models.entities;
using AdminHelper.Models.DbContexts;
using System;
using System.Collections.Generic;

namespace AdminHelper.Infrastructure.Generators
{
    public class EntityGenerator
    {
        private readonly AdminHelperDbContext _context;

        public EntityGenerator(AdminHelperDbContext context)
        {
            _context = context;
        }
        public void AddActors()
        {
            var actors = new List<Actor>
            {
                new Actor { LastName = "Сибиркина", FirstName = "Ольга", Patronymic = "Анатольевна" },
                new Actor { LastName = "Скок", FirstName = "Юлия", Patronymic = "Игоревна" },
                new Actor { LastName = "Грановесов", FirstName = "Сергей", Patronymic = "Владимирович" },
                new Actor { LastName = "Бирюков", FirstName = "Валерий", Patronymic = "Геннадьевич" },
                new Actor { LastName = "Ленских", FirstName = "Тимофей", Patronymic = "Андреевич" },
                new Actor { LastName = "Метелёва", FirstName = "Анна", Patronymic = "Викторовна" },
                new Actor { LastName = "Семёнова", FirstName = "Анастасия", Patronymic = "Аркадьевна" },
                new Actor { LastName = "Свирин", FirstName = "Владимир", Patronymic = "Владимирович" },
                new Actor { LastName = "Протасов", FirstName = "Иван", Patronymic = "Сергеевич" },
                new Actor { LastName = "Ноша", FirstName = "Анастасия", Patronymic = "Вадимовна" },
                new Actor { LastName = "Нечепуренко", FirstName = "Алёна", Patronymic = "Георгиевна" },
                new Actor { LastName = "Шуликова", FirstName = "Татьяна", Patronymic = "Борисовна" },
                new Actor { LastName = "Мастраков", FirstName = "Игорь", Patronymic = "Константинович" },
                new Actor { LastName = "Жаворонкова", FirstName = "Мария", Patronymic = "Игоревна" },
                new Actor { LastName = "Гапоненко", FirstName = "Лидия", Patronymic = "Михайловна" },
                new Actor { LastName = "Якушин", FirstName = "Роман", Patronymic = "Андреевич" },
                new Actor { LastName = "Шалтогачев", FirstName = "Константин", Patronymic = "Васильевич" },
                new Actor { LastName = "Ветров", FirstName = "Вадим", Patronymic = "Дмитриевич" },
                new Actor { LastName = "Глушихина", FirstName = "Таисия", Patronymic = "Николаевна" },
                new Actor { LastName = "Давтян", FirstName = "Максим", Patronymic = "Геннадьевич" },
                new Actor { LastName = "Петроченко", FirstName = "Евгений", Patronymic = "Владимирович" },
                new Actor { LastName = "Семёнова", FirstName = "Ирина", Patronymic = "Валерьевна" },
                new Actor { LastName = "Фадеева", FirstName = "Елена", Patronymic = "Васильевна" },
                new Actor { LastName = "Голдырёв", FirstName = "Егор", Patronymic = "Владимирович" },
                new Actor { LastName = "Гусельников", FirstName = "Вадим", Patronymic = "Алексеевич" },
                new Actor { LastName = "Масалов", FirstName = "Алексей", Patronymic = "Николаевич" }
            };

            _context.Actors.AddRange(actors);
            _context.SaveChanges();
        }

        public void AddRoleTypes()
        {
            var roleTypes = new List<RoleType>
            {
                new RoleType{ Name = "главная" },
                new RoleType{ Name = "второстепенная"  },
                new RoleType{ Name = "массовка" }
            };

            _context.RoleTypes.AddRange(roleTypes);
            _context.SaveChanges();
        }

        public void AddFullness()
        {
            var fullnesses = new List<Fullness>
            {
                new Fullness{ FullnessName = "0-50%", Allowance = 50 },
                new Fullness{ FullnessName = "51-70%", Allowance = 120  },
                new Fullness{ FullnessName = "71-100%", Allowance = 250  },
            };
            _context.FullnessDbSet.AddRange(fullnesses);
            _context.SaveChanges();
        }

        public void AddSpectacles()
        {
            var spectacles = new List<Spectacle>
            {
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-05-01 18:30:00")},
                new Spectacle{ Name = "Подруга жизни", Date = DateTime.Parse("2022-05-06 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-05-07 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-05-07 13:30:00")},
                new Spectacle{ Name = "Диван дальнего следования", Date = DateTime.Parse("2022-05-07 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-05-08 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-05-08 13:30:00")},
                new Spectacle{ Name = "Цилиндр", Date = DateTime.Parse("2022-05-08 18:30:00")},
                new Spectacle{ Name = "Вы еще не замужем? Тогда мы идем к Вам!", Date = DateTime.Parse("2022-05-12 18:30:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-05-14 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-05-14 13:30:00")},
                new Spectacle{ Name = "Прощание в июне", Date = DateTime.Parse("2022-05-14 18:00:00")},
                new Spectacle{ Name = "Сорочинская ярмарка", Date = DateTime.Parse("2022-05-15 18:30:00")},
                new Spectacle{ Name = "Прощание в июне", Date = DateTime.Parse("2022-05-20 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-05-21 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-05-21 13:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-05-21 18:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-05-22 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-05-22 13:30:00")},
                new Spectacle{ Name = "Подруга жизни", Date = DateTime.Parse("2022-05-22 18:00:00")},
                new Spectacle{ Name = "Диван дальнего следования", Date = DateTime.Parse("2022-05-27 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-05-28 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-05-28 13:30:00")},
                new Spectacle{ Name = "Вы еще не замужем? Тогда мы идем к Вам!", Date = DateTime.Parse("2022-05-28 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-05-29 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-05-29 13:30:00")},
                new Spectacle{ Name = "Цилиндр", Date = DateTime.Parse("2022-05-29 18:30:00")},
                new Spectacle{ Name = "Сорочинская ярмарка", Date = DateTime.Parse("2022-06-03 18:30:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-06-04 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-06-04 13:30:00")},
                new Spectacle{ Name = "Диван дальнего следования", Date = DateTime.Parse("2022-06-04 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-06-05 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-06-05 13:30:00")},
                new Spectacle{ Name = "Подруга жизни", Date = DateTime.Parse("2022-06-05 18:00:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-06-09 18:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-06-10 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-06-11 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-06-11 13:30:00")},
                new Spectacle{ Name = "Вы еще не замужем? Тогда мы идем к Вам!", Date = DateTime.Parse("2022-06-11 18:30:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-06-12 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-06-12 13:30:00")},
                new Spectacle{ Name = "Сорочинская ярмарка", Date = DateTime.Parse("2022-06-12 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-06-18 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-06-18 13:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-06-18 18:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-06-19 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-06-19 13:30:00")},
                new Spectacle{ Name = "Диван дальнего следования", Date = DateTime.Parse("2022-06-19 18:30:00")},
                new Spectacle{ Name = "Вы еще не замужем? Тогда мы идем к Вам!", Date = DateTime.Parse("2022-06-24 18:30:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-06-25 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-06-25 13:30:00")},
                new Spectacle{ Name = "Прощание в июне", Date = DateTime.Parse("2022-06-25 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-06-26 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-06-26 13:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-06-26 18:00:00")},
                new Spectacle{ Name = "Сорочинская ярмарка", Date = DateTime.Parse("2022-06-30 18:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-07-01 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-02 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-02 13:30:00")},
                new Spectacle{ Name = "Диван дальнего следования", Date = DateTime.Parse("2022-07-02 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-07-03 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-07-03 13:30:00")},
                new Spectacle{ Name = "Цилиндр", Date = DateTime.Parse("2022-07-03 18:30:00")},
                new Spectacle{ Name = "Вы еще не замужем? Тогда мы идем к Вам!", Date = DateTime.Parse("2022-07-08 18:30:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-07-09 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-07-09 13:30:00")},
                new Spectacle{ Name = "Прощание в июне", Date = DateTime.Parse("2022-07-09 18:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-10 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-10 13:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-07-10 18:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-07-16 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-07-16 13:30:00")},
                new Spectacle{ Name = "Подруга жизни", Date = DateTime.Parse("2022-07-16 18:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-07-17 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-07-17 13:30:00")},
                new Spectacle{ Name = "Вы еще не замужем? Тогда мы идем к Вам!", Date = DateTime.Parse("2022-07-17 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-23 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-23 13:30:00")},
                new Spectacle{ Name = "Цилиндр", Date = DateTime.Parse("2022-07-23 18:30:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-24 11:00:00")},
                new Spectacle{ Name = "Привет,Карлсон!", Date = DateTime.Parse("2022-07-24 13:30:00")},
                new Spectacle{ Name = "Луна над Буффало", Date = DateTime.Parse("2022-07-24 18:00:00")},
                new Spectacle{ Name = "Сорочинская ярмарка", Date = DateTime.Parse("2022-07-29 18:30:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-07-30 11:00:00")},
                new Spectacle{ Name = "Муха Цокотуха", Date = DateTime.Parse("2022-07-30 13:30:00")},
                new Spectacle{ Name = "Диван дальнего следования", Date = DateTime.Parse("2022-07-30 18:30:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-07-31 11:00:00")},
                new Spectacle{ Name = "Буратино", Date = DateTime.Parse("2022-07-31 13:30:00")},
                new Spectacle{ Name = "Подруга жизни", Date = DateTime.Parse("2022-07-31 18:00:00")}
            };

            _context.Spectacles.AddRange(spectacles);
            _context.SaveChanges();
        }

        public void AddRoles()
        {
            var roles = new List<Role>
            {
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 1, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 1, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 1, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 1, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 1, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 1, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 1, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 1, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 1, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 1, Rate = 300 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 2, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 2, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 2, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 2, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 3, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 3, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 3, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 3, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 3, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 3, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 4, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 4, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 4, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 4, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 4, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 4, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 5, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 5, Rate = 800 },
                new Role{ Name = 1 , ActorId = 21, SpectacleId = 5, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 5, Rate = 800 },
                new Role{ Name = 1 , ActorId = 22, SpectacleId = 5, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 5, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 6, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 6, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 6, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 6, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 6, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 6, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 6, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 6, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 6, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 6, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 6, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 6, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 6, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 7, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 7, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 7, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 7, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 7, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 7, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 7, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 7, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 7, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 7, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 7, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 7, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 7, Rate = 300 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 8, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 8, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 8, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 8, Rate = 500 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 8, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 8, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 8, Rate = 800 },
                new Role{ Name = 1 , ActorId = 24, SpectacleId = 8, Rate = 800 },
                new Role{ Name = 1 , ActorId = 7, SpectacleId = 9, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 9, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 9, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 9, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 9, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 10, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 10, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 10, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 10, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 10, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 10, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 10, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 10, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 10, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 11, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 11, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 11, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 11, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 11, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 11, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 11, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 11, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 11, Rate = 500 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 12, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 12, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 12, Rate = 800 },
                new Role{ Name = 1 , ActorId = 26, SpectacleId = 12, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 12, Rate = 800 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 12, Rate = 500 },
                new Role{ Name = 2 , ActorId = 23, SpectacleId = 12, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 12, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 12, Rate = 500 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 13, Rate = 800 },
                new Role{ Name = 1 , ActorId = 14, SpectacleId = 13, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 13, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 13, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 13, Rate = 800 },
                new Role{ Name = 2 , ActorId = 1, SpectacleId = 13, Rate = 500 },
                new Role{ Name = 2 , ActorId = 2, SpectacleId = 13, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 13, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 13, Rate = 500 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 14, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 14, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 14, Rate = 800 },
                new Role{ Name = 1 , ActorId = 26, SpectacleId = 14, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 14, Rate = 800 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 14, Rate = 500 },
                new Role{ Name = 2 , ActorId = 23, SpectacleId = 14, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 14, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 14, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 15, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 15, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 15, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 15, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 15, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 15, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 16, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 16, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 16, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 16, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 16, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 16, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 17, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 17, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 17, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 17, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 17, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 17, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 17, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 17, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 17, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 17, Rate = 300 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 18, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 18, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 18, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 18, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 18, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 18, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 18, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 18, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 18, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 19, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 19, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 19, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 19, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 19, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 19, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 19, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 19, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 19, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 20, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 20, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 20, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 20, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 21, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 21, Rate = 800 },
                new Role{ Name = 1 , ActorId = 21, SpectacleId = 21, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 21, Rate = 800 },
                new Role{ Name = 1 , ActorId = 22, SpectacleId = 21, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 21, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 22, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 22, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 22, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 22, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 22, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 22, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 22, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 22, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 22, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 22, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 22, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 22, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 22, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 23, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 23, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 23, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 23, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 23, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 23, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 23, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 23, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 23, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 23, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 23, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 23, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 23, Rate = 300 },
                new Role{ Name = 1 , ActorId = 7, SpectacleId = 24, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 24, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 24, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 24, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 24, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 25, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 25, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 25, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 25, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 25, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 25, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 26, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 26, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 26, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 26, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 26, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 26, Rate = 500 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 27, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 27, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 27, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 27, Rate = 500 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 27, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 27, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 27, Rate = 800 },
                new Role{ Name = 1 , ActorId = 24, SpectacleId = 27, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 28, Rate = 800 },
                new Role{ Name = 1 , ActorId = 14, SpectacleId = 28, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 28, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 28, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 28, Rate = 800 },
                new Role{ Name = 2 , ActorId = 1, SpectacleId = 28, Rate = 500 },
                new Role{ Name = 2 , ActorId = 2, SpectacleId = 28, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 28, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 28, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 29, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 29, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 29, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 29, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 29, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 29, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 29, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 29, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 29, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 30, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 30, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 30, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 30, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 30, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 30, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 30, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 30, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 30, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 31, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 31, Rate = 800 },
                new Role{ Name = 1 , ActorId = 21, SpectacleId = 31, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 31, Rate = 800 },
                new Role{ Name = 1 , ActorId = 22, SpectacleId = 31, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 31, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 32, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 32, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 32, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 32, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 32, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 32, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 32, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 32, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 32, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 32, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 32, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 32, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 32, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 33, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 33, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 33, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 33, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 33, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 33, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 33, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 33, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 33, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 33, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 33, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 33, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 33, Rate = 300 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 34, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 34, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 34, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 34, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 35, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 35, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 35, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 35, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 35, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 35, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 35, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 35, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 35, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 35, Rate = 300 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 36, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 36, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 36, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 36, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 36, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 36, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 36, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 36, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 36, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 36, Rate = 300 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 37, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 37, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 37, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 37, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 37, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 37, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 38, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 38, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 38, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 38, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 38, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 38, Rate = 500 },
                new Role{ Name = 1 , ActorId = 7, SpectacleId = 39, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 39, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 39, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 39, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 39, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 40, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 40, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 40, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 40, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 40, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 40, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 40, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 40, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 40, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 41, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 41, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 41, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 41, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 41, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 41, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 41, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 41, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 41, Rate = 500 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 42, Rate = 800 },
                new Role{ Name = 1 , ActorId = 14, SpectacleId = 42, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 42, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 42, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 42, Rate = 800 },
                new Role{ Name = 2 , ActorId = 1, SpectacleId = 42, Rate = 500 },
                new Role{ Name = 2 , ActorId = 2, SpectacleId = 42, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 42, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 42, Rate = 500 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 43, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 43, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 43, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 43, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 43, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 43, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 43, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 43, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 43, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 43, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 43, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 43, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 43, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 44, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 44, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 44, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 44, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 44, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 44, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 44, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 44, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 44, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 44, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 44, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 44, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 44, Rate = 300 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 45, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 45, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 45, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 45, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 45, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 45, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 45, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 45, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 45, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 45, Rate = 300 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 46, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 46, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 46, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 46, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 46, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 46, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 47, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 47, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 47, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 47, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 47, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 47, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 48, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 48, Rate = 800 },
                new Role{ Name = 1 , ActorId = 21, SpectacleId = 48, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 48, Rate = 800 },
                new Role{ Name = 1 , ActorId = 22, SpectacleId = 48, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 48, Rate = 800 },
                new Role{ Name = 1 , ActorId = 7, SpectacleId = 49, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 49, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 49, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 49, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 49, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 50, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 50, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 50, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 50, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 50, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 50, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 50, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 50, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 50, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 51, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 51, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 51, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 51, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 51, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 51, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 51, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 51, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 51, Rate = 500 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 52, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 52, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 52, Rate = 800 },
                new Role{ Name = 1 , ActorId = 26, SpectacleId = 52, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 52, Rate = 800 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 52, Rate = 500 },
                new Role{ Name = 2 , ActorId = 23, SpectacleId = 52, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 52, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 52, Rate = 500 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 53, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 53, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 53, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 53, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 53, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 53, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 53, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 53, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 53, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 53, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 53, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 53, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 53, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 54, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 54, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 54, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 54, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 54, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 54, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 54, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 54, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 54, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 54, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 54, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 54, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 54, Rate = 300 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 55, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 55, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 55, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 55, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 55, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 55, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 55, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 55, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 55, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 55, Rate = 300 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 56, Rate = 800 },
                new Role{ Name = 1 , ActorId = 14, SpectacleId = 56, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 56, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 56, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 56, Rate = 800 },
                new Role{ Name = 2 , ActorId = 1, SpectacleId = 56, Rate = 500 },
                new Role{ Name = 2 , ActorId = 2, SpectacleId = 56, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 56, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 56, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 57, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 57, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 57, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 57, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 57, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 57, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 57, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 57, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 57, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 57, Rate = 300 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 58, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 58, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 58, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 58, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 58, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 58, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 59, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 59, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 59, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 59, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 59, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 59, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 60, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 60, Rate = 800 },
                new Role{ Name = 1 , ActorId = 21, SpectacleId = 60, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 60, Rate = 800 },
                new Role{ Name = 1 , ActorId = 22, SpectacleId = 60, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 60, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 61, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 61, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 61, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 61, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 61, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 61, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 61, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 61, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 61, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 61, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 61, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 61, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 61, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 62, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 62, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 62, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 62, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 62, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 62, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 62, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 62, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 62, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 62, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 62, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 62, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 62, Rate = 300 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 63, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 63, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 63, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 63, Rate = 500 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 63, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 63, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 63, Rate = 800 },
                new Role{ Name = 1 , ActorId = 24, SpectacleId = 63, Rate = 800 },
                new Role{ Name = 1 , ActorId = 7, SpectacleId = 64, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 64, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 64, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 64, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 64, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 65, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 65, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 65, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 65, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 65, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 65, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 65, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 65, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 65, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 66, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 66, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 66, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 66, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 66, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 66, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 66, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 66, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 66, Rate = 500 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 67, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 67, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 67, Rate = 800 },
                new Role{ Name = 1 , ActorId = 26, SpectacleId = 67, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 67, Rate = 800 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 67, Rate = 500 },
                new Role{ Name = 2 , ActorId = 23, SpectacleId = 67, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 67, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 67, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 68, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 68, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 68, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 68, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 68, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 68, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 69, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 69, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 69, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 69, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 69, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 69, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 70, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 70, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 70, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 70, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 70, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 70, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 70, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 70, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 70, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 70, Rate = 300 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 71, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 71, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 71, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 71, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 71, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 71, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 71, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 71, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 71, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 72, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 72, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 72, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 72, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 72, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 72, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 72, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 72, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 72, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 73, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 73, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 73, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 73, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 74, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 74, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 74, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 74, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 74, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 74, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 74, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 74, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 74, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 74, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 74, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 74, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 74, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 75, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 75, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 75, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 75, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 75, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 75, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 75, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 75, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 75, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 75, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 75, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 75, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 75, Rate = 300 },
                new Role{ Name = 1 , ActorId = 7, SpectacleId = 76, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 76, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 76, Rate = 800 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 76, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 76, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 77, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 77, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 77, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 77, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 77, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 77, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 78, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 78, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 78, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 78, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 78, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 78, Rate = 500 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 79, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 79, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 79, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 79, Rate = 500 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 79, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 79, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 79, Rate = 800 },
                new Role{ Name = 1 , ActorId = 24, SpectacleId = 79, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 80, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 80, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 80, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 80, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 80, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 80, Rate = 500 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 1 , ActorId = 10, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 1 , ActorId = 11, SpectacleId = 81, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 81, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 81, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 81, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 81, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 81, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 82, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 82, Rate = 800 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 82, Rate = 800 },
                new Role{ Name = 1 , ActorId = 1, SpectacleId = 82, Rate = 800 },
                new Role{ Name = 1 , ActorId = 25, SpectacleId = 82, Rate = 800 },
                new Role{ Name = 2 , ActorId = 4, SpectacleId = 82, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 82, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 82, Rate = 500 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 82, Rate = 300 },
                new Role{ Name = 3 , ActorId = 12, SpectacleId = 82, Rate = 300 },
                new Role{ Name = 1 , ActorId = 13, SpectacleId = 83, Rate = 800 },
                new Role{ Name = 1 , ActorId = 14, SpectacleId = 83, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 83, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 83, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 83, Rate = 800 },
                new Role{ Name = 2 , ActorId = 1, SpectacleId = 83, Rate = 500 },
                new Role{ Name = 2 , ActorId = 2, SpectacleId = 83, Rate = 500 },
                new Role{ Name = 2 , ActorId = 17, SpectacleId = 83, Rate = 500 },
                new Role{ Name = 2 , ActorId = 9, SpectacleId = 83, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 84, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 84, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 84, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 84, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 84, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 84, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 84, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 84, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 84, Rate = 500 },
                new Role{ Name = 1 , ActorId = 6, SpectacleId = 85, Rate = 800 },
                new Role{ Name = 1 , ActorId = 18, SpectacleId = 85, Rate = 800 },
                new Role{ Name = 1 , ActorId = 3, SpectacleId = 85, Rate = 800 },
                new Role{ Name = 1 , ActorId = 2, SpectacleId = 85, Rate = 800 },
                new Role{ Name = 1 , ActorId = 8, SpectacleId = 85, Rate = 800 },
                new Role{ Name = 2 , ActorId = 14, SpectacleId = 85, Rate = 500 },
                new Role{ Name = 2 , ActorId = 7, SpectacleId = 85, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 85, Rate = 500 },
                new Role{ Name = 2 , ActorId = 16, SpectacleId = 85, Rate = 500 },
                new Role{ Name = 1 , ActorId = 5, SpectacleId = 86, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 86, Rate = 800 },
                new Role{ Name = 1 , ActorId = 21, SpectacleId = 86, Rate = 800 },
                new Role{ Name = 1 , ActorId = 12, SpectacleId = 86, Rate = 800 },
                new Role{ Name = 1 , ActorId = 22, SpectacleId = 86, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 86, Rate = 800 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 87, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 87, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 87, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 87, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 87, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 87, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 87, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 87, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 87, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 87, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 87, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 87, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 87, Rate = 300 },
                new Role{ Name = 1 , ActorId = 17, SpectacleId = 88, Rate = 800 },
                new Role{ Name = 1 , ActorId = 16, SpectacleId = 88, Rate = 800 },
                new Role{ Name = 1 , ActorId = 20, SpectacleId = 88, Rate = 800 },
                new Role{ Name = 1 , ActorId = 4, SpectacleId = 88, Rate = 800 },
                new Role{ Name = 1 , ActorId = 23, SpectacleId = 88, Rate = 800 },
                new Role{ Name = 2 , ActorId = 5, SpectacleId = 88, Rate = 500 },
                new Role{ Name = 2 , ActorId = 15, SpectacleId = 88, Rate = 500 },
                new Role{ Name = 2 , ActorId = 10, SpectacleId = 88, Rate = 500 },
                new Role{ Name = 2 , ActorId = 18, SpectacleId = 88, Rate = 500 },
                new Role{ Name = 3 , ActorId = 21, SpectacleId = 88, Rate = 300 },
                new Role{ Name = 3 , ActorId = 14, SpectacleId = 88, Rate = 300 },
                new Role{ Name = 3 , ActorId = 11, SpectacleId = 88, Rate = 300 },
                new Role{ Name = 3 , ActorId = 19, SpectacleId = 88, Rate = 300 },
            };

            _context.AddRange(roles);
            _context.SaveChanges();
        }
    }
}
